// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: address.sql

package db

import (
	"context"
)

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, street_number, street_name, city, state, zipcode FROM addresses
WHERE id = $1
`

func (q *Queries) GetAddressByID(ctx context.Context, id int32) (Address, error) {
	row := q.db.QueryRowContext(ctx, getAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.StreetNumber,
		&i.StreetName,
		&i.City,
		&i.State,
		&i.Zipcode,
	)
	return i, err
}
